spring:
  application:
    name: p2p-lending

  datasource:
    url: jdbc:postgresql://localhost:5432/p2p-lending
    username: postgres
    password: NOVIANTO

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/p2p-lending-logs
